"""View mode toggle bar — switches between Input/Alpha/FG/Matte/Comp/Processed.

Uses QButtonGroup with exclusive selection. Active button highlighted
with brand yellow. Buttons are enabled/disabled based on which output
directories actually have frames (via FrameIndex availability).
"""
from __future__ import annotations

from PySide6.QtWidgets import QWidget, QHBoxLayout, QPushButton, QButtonGroup
from PySide6.QtCore import Signal

from ui.preview.frame_index import ViewMode


# Display labels for each mode
_MODE_LABELS: dict[ViewMode, str] = {
    ViewMode.INPUT: "INPUT",
    ViewMode.MASK: "MASK",
    ViewMode.ALPHA: "ALPHA",
    ViewMode.FG: "FG",
    ViewMode.MATTE: "MATTE",
    ViewMode.COMP: "COMP",
    ViewMode.PROCESSED: "PROC",
}

_MODE_TOOLTIPS: dict[ViewMode, str] = {
    ViewMode.INPUT: "Original input footage (unprocessed)",
    ViewMode.MASK: (
        "Tracked mask — SAM2 segmentation output.\n"
        "White = foreground, black = background.\n"
        "This is the binary mask before MatAnyone2/VideoMaMa refinement."
    ),
    ViewMode.ALPHA: (
        "Alpha hint — generated by GVM, VideoMaMa, or MatAnyone2.\n"
        "White = foreground, black = background.\n"
        "This is the pre-inference guide used by CorridorKey."
    ),
    ViewMode.FG: (
        "Foreground — subject with green spill removed.\n"
        "Colors may look shifted; this is the despilled intermediate."
    ),
    ViewMode.MATTE: (
        "Alpha matte — white = opaque, black = transparent.\n"
        "Shows the AI's confidence in foreground vs background."
    ),
    ViewMode.COMP: (
        "Composite — final keyed result over checkerboard.\n"
        "Best preview of key quality with faithful colors."
    ),
    ViewMode.PROCESSED: (
        "Processed — production RGBA (straight, linear).\n"
        "For Resolve, Premiere, and compositing tools.\n"
        "Preview composites the stored image over black.\n"
        "Final compositing should happen in your compositor of choice."
    ),
}


class ViewModeBar(QWidget):
    """Horizontal bar of toggle buttons for preview view modes."""

    mode_changed = Signal(str)  # emits ViewMode.value

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setFixedHeight(30)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(8, 2, 8, 2)
        layout.setSpacing(2)

        self._button_group = QButtonGroup(self)
        self._button_group.setExclusive(True)
        self._buttons: dict[ViewMode, QPushButton] = {}

        for i, mode in enumerate(ViewMode):
            btn = QPushButton(_MODE_LABELS[mode])
            btn.setCheckable(True)
            btn.setEnabled(False)
            btn.setFixedHeight(24)
            btn.setMinimumWidth(50)
            btn.setStyleSheet(self._button_style(False))
            btn.setToolTip(_MODE_TOOLTIPS.get(mode, ""))
            self._buttons[mode] = btn
            self._button_group.addButton(btn, i)
            layout.addWidget(btn)

        # Default to COMP
        self._buttons[ViewMode.COMP].setChecked(True)

        self._button_group.idClicked.connect(self._on_mode_clicked)
        layout.addStretch()


    def set_available_modes(self, modes: list[ViewMode]) -> None:
        """Enable buttons for modes that have frames."""
        mode_set = set(modes)
        for mode, btn in self._buttons.items():
            btn.setEnabled(mode in mode_set)

        # If current mode is unavailable, switch to the most useful fallback.
        current = self.current_mode()
        if current not in mode_set and mode_set:
            # Prefer final outputs first, then AlphaHint, then source views.
            for fallback in [ViewMode.COMP, ViewMode.ALPHA, ViewMode.INPUT]:
                if fallback in mode_set:
                    self._buttons[fallback].setChecked(True)
                    self._on_mode_clicked(list(ViewMode).index(fallback))
                    return
            first = list(mode_set)[0]
            self._buttons[first].setChecked(True)
            self._on_mode_clicked(list(ViewMode).index(first))

    def current_mode(self) -> ViewMode:
        """Return the currently selected ViewMode."""
        checked_id = self._button_group.checkedId()
        if checked_id >= 0:
            return list(ViewMode)[checked_id]
        return ViewMode.COMP

    def _on_mode_clicked(self, button_id: int) -> None:
        mode = list(ViewMode)[button_id]
        # Update button styles
        for m, btn in self._buttons.items():
            btn.setStyleSheet(self._button_style(m == mode))
        self.mode_changed.emit(mode.value)

    @staticmethod
    def _button_style(active: bool) -> str:
        if active:
            return (
                "QPushButton { background-color: #FFF203; color: #000000; "
                "font-weight: 700; font-size: 10px; padding: 2px 6px; border: none; }"
            )
        return (
            "QPushButton { background-color: #1A1900; color: #808070; "
            "font-size: 10px; padding: 2px 6px; border: 1px solid #2A2910; }"
            "QPushButton:hover { border-color: #454430; color: #E0E0E0; }"
            "QPushButton:disabled { color: #3A3A30; border-color: #1A1900; }"
        )
